//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LSDBEntities : DbContext
    {
        public LSDBEntities()
            : base("name=LSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBaseInf> TBaseInfs { get; set; }
        public virtual DbSet<TBaseInfType> TBaseInfTypes { get; set; }
        public virtual DbSet<TBrand> TBrands { get; set; }
        public virtual DbSet<TCarType> TCarTypes { get; set; }
        public virtual DbSet<TCat> TCats { get; set; }
        public virtual DbSet<TCatCarType> TCatCarTypes { get; set; }
        public virtual DbSet<TCustomer> TCustomers { get; set; }
        public virtual DbSet<TDocSerial> TDocSerials { get; set; }
        public virtual DbSet<TExitFromWarehouseDetail> TExitFromWarehouseDetails { get; set; }
        public virtual DbSet<TExitFromWarehouseHeader> TExitFromWarehouseHeaders { get; set; }
        public virtual DbSet<TFactorDetail> TFactorDetails { get; set; }
        public virtual DbSet<TFactorHeader> TFactorHeaders { get; set; }
        public virtual DbSet<TGoodsGrade> TGoodsGrades { get; set; }
        public virtual DbSet<TGoodsPrice> TGoodsPrices { get; set; }
        public virtual DbSet<TGoodsPriceArc> TGoodsPriceArcs { get; set; }
        public virtual DbSet<TInventoryDocDetail> TInventoryDocDetails { get; set; }
        public virtual DbSet<TInventoryDocHeader> TInventoryDocHeaders { get; set; }
        public virtual DbSet<TInventoryDocType> TInventoryDocTypes { get; set; }
        public virtual DbSet<TInvoiceDetail> TInvoiceDetails { get; set; }
        public virtual DbSet<TInvoiceHeader> TInvoiceHeaders { get; set; }
        public virtual DbSet<TItemGroup> TItemGroups { get; set; }
        public virtual DbSet<TItemType> TItemTypes { get; set; }
        public virtual DbSet<TOrder> TOrders { get; set; }
        public virtual DbSet<TOrderHaveError> TOrderHaveErrors { get; set; }
        public virtual DbSet<TPackingList> TPackingLists { get; set; }
        public virtual DbSet<TPackingListError> TPackingListErrors { get; set; }
        public virtual DbSet<TRequestDetial> TRequestDetials { get; set; }
        public virtual DbSet<TRequestHeader> TRequestHeaders { get; set; }
        public virtual DbSet<TSerial> TSerials { get; set; }
        public virtual DbSet<TUploadInf> TUploadInfs { get; set; }
        public virtual DbSet<TUsageType> TUsageTypes { get; set; }
        public virtual DbSet<TWareHouseStock> TWareHouseStocks { get; set; }
        public virtual DbSet<V_ExitWarehouse> V_ExitWarehouse { get; set; }
        public virtual DbSet<V_ExitWarehouseHeader> V_ExitWarehouseHeader { get; set; }
        public virtual DbSet<V_Invoice> V_Invoice { get; set; }
        public virtual DbSet<VCat> VCats { get; set; }
        public virtual DbSet<VCatCarType> VCatCarTypes { get; set; }
        public virtual DbSet<VCustomer> VCustomers { get; set; }
        public virtual DbSet<VFactor> VFactors { get; set; }
        public virtual DbSet<VGoodsPrice> VGoodsPrices { get; set; }
        public virtual DbSet<VGoodsPriceArc> VGoodsPriceArcs { get; set; }
        public virtual DbSet<VRequest> VRequests { get; set; }
        public virtual DbSet<VWareHouseStock> VWareHouseStocks { get; set; }
    }
}
