//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCat
    {
        public int ID { get; set; }
        public string TechnicalCode { get; set; }
        public string PNC { get; set; }
        public string ItemName { get; set; }
        public string PersianName { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public double NetWeight { get; set; }
        public string ForWardItemNo { get; set; }
        public string ForWardITCCode { get; set; }
        public string BackwardItemNo { get; set; }
        public string BackwardITCCode { get; set; }
        public double QuantityOfUsageInMachine { get; set; }
        public double PPLDollar { get; set; }
        public double BasePriceRls { get; set; }
        public string ItemGroup { get; set; }
        public string Brand { get; set; }
        public string Health { get; set; }
        public string Grade { get; set; }
        public string ItemUsage { get; set; }
        public string UsagePlace { get; set; }
        public string Specificcode { get; set; }
        public string VeryCritical { get; set; }
        public int ItemGroupId { get; set; }
        public int ItemTypeId { get; set; }
        public int GoodsGradeId { get; set; }
        public int TrackingTypeId { get; set; }
        public int LabelingTypeId { get; set; }
        public int UsageTypeId { get; set; }
        public int UnitId { get; set; }
    }
}
