//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCustomer
    {
        public int CustomerId { get; set; }
        public int CustomerTypeId { get; set; }
        public int CustomerContractTypeId { get; set; }
        public string CustomerName { get; set; }
        public string Tel { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string ManagerName { get; set; }
        public short IsActive { get; set; }
        public string NationalId { get; set; }
        public string ZIPCode { get; set; }
        public string EcoCode { get; set; }
        public string RegistrationNumber { get; set; }
        public string RepresentativeCode { get; set; }
        public string RepresentativeName { get; set; }
    }
}
