//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDocSerial
    {
        public int Id { get; set; }
        public int DocSerialNo { get; set; }
        public int CurYear { get; set; }
        public int InventoryDocTypeId { get; set; }
    }
}
