//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TExitFromWarehouseDetail
    {
        public int ExitFromWarehouseDetailId { get; set; }
        public string ExitNo { get; set; }
        public string TechnicalCode { get; set; }
        public double Qty { get; set; }
        public short IsActive { get; set; }
        public int InvoiceDetailId { get; set; }
        public string FactorNo { get; set; }
        public string FactorDate { get; set; }
        public string FactorTime { get; set; }
        public string FactorEntryDataPersonalId { get; set; }
    }
}
