//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TExitFromWarehouseHeader
    {
        public int ExitFromWarehouseHeaderId { get; set; }
        public string InvoiceNo { get; set; }
        public string ExitNo { get; set; }
        public int CustomerId { get; set; }
        public string ExitDate { get; set; }
        public string ExitTime { get; set; }
        public string EntryPersonalId { get; set; }
        public short IsActive { get; set; }
        public int InvoiceId { get; set; }
        public string ExitTitle { get; set; }
    }
}
