//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGoodsPrice
    {
        public int GoodsPriceId { get; set; }
        public string TechnicalCode { get; set; }
        public int CurrencyTypeId { get; set; }
        public double DollarPrice { get; set; }
        public Nullable<double> BasePrice { get; set; }
        public double PriceInRials { get; set; }
        public string EntryDataDate { get; set; }
        public string EntryDataTime { get; set; }
        public string EntryPersonalId { get; set; }
    }
}
