//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TInventoryDocDetail
    {
        public int InventoryDocDetailId { get; set; }
        public int InventoryDocHeaderId { get; set; }
        public string TechnicalCode { get; set; }
        public int OrderId { get; set; }
        public int PackingListId { get; set; }
        public double Qty { get; set; }
        public string Explain { get; set; }
    
        public virtual TInventoryDocHeader TInventoryDocHeader { get; set; }
    }
}
