//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TInventoryDocHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TInventoryDocHeader()
        {
            this.TInventoryDocDetails = new HashSet<TInventoryDocDetail>();
        }
    
        public int InventoryDocHeaderId { get; set; }
        public string DocNo { get; set; }
        public int InventoryDocTypeId { get; set; }
        public string EntryDataDate { get; set; }
        public string EntryDataTime { get; set; }
        public string EntryDataPersonalId { get; set; }
        public short IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TInventoryDocDetail> TInventoryDocDetails { get; set; }
    }
}
