//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOrder
    {
        public int OrderId { get; set; }
        public string TechnicalCode { get; set; }
        public double Quantity { get; set; }
        public double Price { get; set; }
        public double PriceAED { get; set; }
        public string Tariff { get; set; }
        public double NetWeight { get; set; }
        public double GrossWeight { get; set; }
        public string OrderNo { get; set; }
        public string EntryDataDate { get; set; }
        public string EntryDataTime { get; set; }
        public string EntryDataPersonalId { get; set; }
        public int UploadInfId { get; set; }
        public double PackListQTY { get; set; }
        public string PackingListTechnicalCode { get; set; }
        public double RecieveOrderQuantity { get; set; }
        public short IsActive { get; set; }
    }
}
