//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUploadInf
    {
        public int UploadInfId { get; set; }
        public string DocPath { get; set; }
        public string EntryPersonalId { get; set; }
        public int UploadDocTypeId { get; set; }
        public string DocTitle { get; set; }
        public string DocDesc { get; set; }
    }
}
