//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ExitWarehouse
    {
        public int ExitFromWarehouseDetailId { get; set; }
        public string TechnicalCode { get; set; }
        public string ItemName { get; set; }
        public short ExitDetailIsActive { get; set; }
        public string InvoiceNo { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string ExitDate { get; set; }
        public string ExitTime { get; set; }
        public string EntryPersonalId { get; set; }
        public short ExitHeaderIsActive { get; set; }
        public string ExitNo { get; set; }
        public int InvoiceId { get; set; }
        public string ExitTitle { get; set; }
        public string ExitHeaderIsActiveDesc { get; set; }
        public string ExitDetailIsActiveDesc { get; set; }
        public double Qty { get; set; }
        public int InvoiceDetailId { get; set; }
        public string InvoiceTitle { get; set; }
        public int ExitFromWarehouseHeaderId { get; set; }
        public double PriceInRials { get; set; }
        public string FactorNo { get; set; }
        public string FactorDate { get; set; }
        public string FactorTime { get; set; }
        public string FactorEntryDataPersonalId { get; set; }
    }
}
