//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCat
    {
        public int ID { get; set; }
        public string TechnicalCode { get; set; }
        public string PNC { get; set; }
        public string ItemName { get; set; }
        public string PersianName { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public double NetWeight { get; set; }
        public int ItemGroupId { get; set; }
        public string ItemGroupDesc { get; set; }
        public int ItemTypeId { get; set; }
        public string ItemTypeDesc { get; set; }
        public int GoodsGradeId { get; set; }
        public string GoodsGradeDesc { get; set; }
        public int TrackingTypeId { get; set; }
        public string TrackingDesc { get; set; }
        public int LabelingTypeId { get; set; }
        public string LabelingDesc { get; set; }
        public int UsageTypeId { get; set; }
        public string UsageTypeDesc { get; set; }
        public int UnitId { get; set; }
        public string UnitDesc { get; set; }
    }
}
