//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VFactor
    {
        public int FactorHeaderId { get; set; }
        public int InvoiceId { get; set; }
        public string FactorNo { get; set; }
        public string FactorDate { get; set; }
        public string FactorTime { get; set; }
        public string EntryPersonalId { get; set; }
        public short IsActive { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public int FactorDetailId { get; set; }
        public string TechnicalCode { get; set; }
        public double Qty { get; set; }
        public short EXPR1 { get; set; }
        public int InvoiceDetailId { get; set; }
        public double Price { get; set; }
        public string ItemName { get; set; }
    }
}
