//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRequest
    {
        public string TechnicalCode { get; set; }
        public string ItemName { get; set; }
        public string PersianName { get; set; }
        public int UnitId { get; set; }
        public string UnitDesc { get; set; }
        public double Qty { get; set; }
        public double ConfirmQty { get; set; }
        public short RequestDetailIsActive { get; set; }
        public string RequestNo { get; set; }
        public string RequestDate { get; set; }
        public string RequestTime { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string EntryPersonalId { get; set; }
        public string RequestTypeDesc { get; set; }
        public string RequestTitle { get; set; }
        public short RequestHeaderIsActive { get; set; }
        public int RequestDetialId { get; set; }
        public int RequestId { get; set; }
        public int RequestTypeId { get; set; }
        public double StockQty { get; set; }
        public double ReserveQty { get; set; }
        public double BlockedQty { get; set; }
        public double ScrapeQty { get; set; }
        public double InvoiceQty { get; set; }
    }
}
