//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWareHouseStock
    {
        public string TechnicalCode { get; set; }
        public string ItemName { get; set; }
        public string PersianName { get; set; }
        public int UnitId { get; set; }
        public string UnitDesc { get; set; }
        public Nullable<double> ReserveQty { get; set; }
        public Nullable<double> BlockedQty { get; set; }
        public Nullable<double> ScrapeQty { get; set; }
        public Nullable<double> StockQty { get; set; }
    }
}
